### PR TITLE
firewall_config: molecule testing for firewall-config role

### PR DESCRIPTION
**Pull request by Sheersha-jain**

### CODE REVIEW

**Comment by Sheersha-jain** [comment]
@sac can you please review this.

**Comment by Sheersha-jain** [comment]
I am also getting this ansible lint error while running the molecule test on code.

    --> Executing Ansible Lint on /root/my-work/gluster-ansible-infra/roles/firewall_config/molecule/default                                      /playbook.yml...
    
    [ANSIBLE0012] Commands should not change things if nothing needs doing
    /root/my-work/gluster-ansible-infra/roles/firewall_config/tasks/main.yml:34
    Task/Handler: Reload the firewall
    
    [ANSIBLE0013] Use shell only when shell functionality is required
    /root/my-work/gluster-ansible-infra/roles/firewall_config/tasks/main.yml:34
    Task/Handler: Reload the firewall
    
    An error occurred during the test sequence action: 'lint'. Cleaning up.

**Comment by sac** [comment]
@Sheersha-jain I have fixed this issue as part of commit: https://github.com/gluster/gluster-ansible-infra/pull/28/commits/2b7dd8b

Can you apply that patch and try?

**Comment by Sheersha-jain** [comment]
@sac the error still persists 

     Lint completed successfully.
     --> Executing Ansible Lint on /root/my-work/gluster-ansible-infra/roles/firewall_config/molecule/defaul/playbook.yml...     
    [ANSIBLE0013] Use shell only when shell functionality is required
    /root/my-work/gluster-ansible-infra/roles/firewall_config/tasks/main.yml:34
    Task/Handler: Reload the firewall
    
    [ANSIBLE0016] Tasks that run when changed should likely be handlers
    /root/my-work/gluster-ansible-infra/roles/firewall_config/tasks/main.yml:34
    Task/Handler: Reload the firewall

**Comment by nigelbabu** [comment]
@sac You might want to move that into a handler instead which should handle this seamlessly.

**Comment by sac** [comment]
@nigelbabu ack! I will change this.

**Comment by Sheersha-jain** [comment]
@sac  I updated the code with handler file and it is working fine, and I removed pyc file as well. But now I am getting merge conflicts because #31 is not merged.

**Comment by nigelbabu** [comment]
Can you add `*.pyc` to `.gitignore` (create the file if it doesn't exist). That should prevent accidentally committing it.

**Comment by Sheersha-jain** [comment]
@nigelbabu added .gitignore file.

**Comment by sac** [comment]
@Sheersha-jain I merged the handler part. Can you rebase and push the changes.

The changes look good. I'll commit once you rebase.

**Pull request merged**
